import type { Budget, CardFitBasis, CardValue, RecurringMerchant, Transaction, TransactionDateRange } from "@/lib/types";
import type { TransactionFilter, TransactionSort, View } from "@/lib/app/types";

export type ActiveViewProps = {
  activeView: View;
  availableBalance: number | null;
  budgets: Budget[];
  cardBasis: CardFitBasis;
  cardFitSourceLabel: string;
  cardFitWindowLabel: string;
  cards: CardValue[];
  categories: { category: string; amount: number }[];
  chartCategories: { category: string; amount: number }[];
  chartTotal: number;
  completeAkahuConnection: (responseValue?: string) => Promise<void>;
  connectionResponse: string;
  expensesCount: number;
  hasCardEligibleSpend: boolean;
  hoveredCategory: string | null;
  income: number;
  insights: string[];
  isConnected: boolean;
  isLoadingMoreTransactions: boolean;
  isLoadingTransactions: boolean;
  monthlySpend: number;
  onCreateCategory: (category: string) => void;
  onCategoryChange: (transactionId: string, category: string) => void;
  onConnectionResponseChange: (value: string) => void;
  onLoadMoreTransactions: () => void;
  onRefreshUserTransactions: () => void;
  query: string;
  recurring: RecurringMerchant[];
  reviewCount: number;
  safeToSpendAmount: number;
  setActiveView: (view: View) => void;
  setHoveredCategory: (category: string | null) => void;
  setQuery: (query: string) => void;
  setSyncResult: (value: string) => void;
  setTransactionCategory: (categories: string[]) => void;
  setTransactionDateRange: (dateRange: TransactionDateRange) => void;
  setTransactionFilter: (filter: TransactionFilter) => void;
  setTransactionSort: (sort: TransactionSort) => void;
  syncResult: string;
  transactionCategory: string[];
  transactionCategoryOptions: string[];
  transactionDateRange: TransactionDateRange;
  transactionFilter: TransactionFilter;
  transactionsHasMore: boolean;
  transactionPreview: Transaction[];
  transactionSort: TransactionSort;
  upcomingCount: number;
  upcomingTotal: number;
  visibleTransactions: Transaction[];
  workingTransactions: Transaction[];
  categoryColors: Record<string, string>;
  updateCategoryColor: (category: string, color: string) => void;
  deleteCategory: (category: string) => void;
};
